include:
- template: Security/Dependency-Scanning.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml
- template: Code-Quality.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml
stages:
- lint
- test
variables:
  POSTGRES_USER: scram
  POSTGRES_PASSWORD: ''
  POSTGRES_DB: test_scram
  POSTGRES_HOST_AUTH_METHOD: trust
  CELERY_BROKER_URL: redis://redis:6379/0
flake8:
  stage: lint
  image: python:3.8-alpine
  before_script:
  - pip install -q flake8
  script:
  - flake8
pytest:
  stage: test
  image: docker/compose:latest
  services:
  - docker:dind
  before_script:
  - apk add make
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - export COMPOSE_PROJECT_NAME=$CI_PIPELINE_ID
  - ".ci-scripts/pull_images.sh"
  - make toggle-prod
  - docker-compose -f active.yml build --no-cache django
  - make build
  - ".ci-scripts/push_images.sh"
  - make migrate
  - make run
  script:
  - make pytest
  - make behave-all
  after_script:
  - make clean
gemnasium-dependency_scanning:
  variables:
    PIP_REQUIREMENTS_FILE: requirements/base.txt
code_quality_html:
  extends: code_quality
  variables:
    REPORT_FORMAT: html
  artifacts:
    paths:
    - gl-code-quality-report.html
sast:
  stage: test
