stages:
  - builder_image
  - test

builder_image:
  stage: builder_image
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $IMAGE_NAME:latest

test:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/scram_test:latest
  script:
    # this configures Django application to use attached postgres database that is run on `postgres` host
    # - export DATABASE_URL=postgres://postgres:@postgres:5432/python-test-app
    - python3 manage.py test
    - python3 scram/functional_tests.py