# You can override the included template(s) by including variable overrides
# See https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
include:
- template: Dependency-Scanning.gitlab-ci.yml
- template: Code-Quality.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml
stages:
- lint
- test
variables:
  POSTGRES_USER: scram
  POSTGRES_PASSWORD: ''
  POSTGRES_DB: test_scram
  POSTGRES_HOST_AUTH_METHOD: trust
  CELERY_BROKER_URL: redis://redis:6379/0
flake8:
  stage: lint
  image: python:3.8-alpine
  before_script:
  - pip install -q flake8
  script:
  - flake8
pytest:
  stage: test
  image: docker/compose:latest
  services:
  - docker:dind
  before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - export COMPOSE_PROJECT_NAME=$CI_PIPELINE_ID
  - ".ci-scripts/pull_images.sh"
  - docker-compose -f local.yml build
  - ".ci-scripts/push_images.sh"
  - docker-compose -f local.yml run --rm django python manage.py migrate
  - docker-compose -f local.yml up -d
  script:
  - docker-compose -f local.yml run django pytest
  - docker-compose -f local.yml run django python manage.py behave --no-input
  after_script:
  - docker-compose -f local.yml rm --force --stop
gemnasium-dependency_scanning:
  variables:
    PIP_REQUIREMENTS_FILE: requirements/base.txt
code_quality_html:
  extends: code_quality
  variables:
    REPORT_FORMAT: html
  artifacts:
    paths:
    - gl-code-quality-report.html
sast:
  stage: test
