---
- hosts: scram
  tasks:
    - block:
      - name: Create SCRAM group
        group:
          name: "{{ scram_user }}"
          state: present

      - name: Create SCRAM user
        user:
          name: "{{ scram_user }}"
          comment: "SCRAM User"
          group: "{{ scram_group }}"
          uid: "{{ scram_uid }}"
      when: '"mac" not in group_names and scram_install_user'

    - name: Clone SCRAM repository
      git:
        repo: https://gitlab.es.net/security/scram.git
        dest: "{{ scram_home }}"
        version: "{{ scram_code_branch }}"
        force: true

    - name: Create production .env files
      file:
        path: "{{ scram_home }}/.envs/.production"
        state: directory
        owner: "{{ scram_user }}"
        group: "{{ scram_group }}"

    - name: Deploy environment variable templates
      template:
        src: "ansible/{{ item }}.env.j2"
        dest: "{{ scram_home }}/.envs/.production/.{{ item }}"
        owner: "{{ scram_user }}"
        group: "{{ scram_group }}"
      loop:
        - django
        - postgres

    - name: Deploy traefik config file
      template:
        src: "ansible/traefik.yml.j2"
        dest: "{{ scram_home }}/compose/production/traefik/traefik.yml"
        owner: "{{ scram_user }}"
        group: "{{ scram_group }}"

    - name: Turn off old containers
      docker_compose:
        project_src: "{{ scram_home }}"
        files: production.yml
        state: absent
      failed_when: false

    - name: Start docker-compose
      docker_compose:
        project_src: "{{ scram_home }}"
        files: production.yml

    - name: Run django migrations and collectstatic
      command: "docker-compose -f production.yml run django python manage.py {{ item }}"
      args:
        chdir: "{{ scram_home }}"
      loop:
        - makemigrations
        - migrate
        - collectstatic
      tags:
        - migrations
