version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_redis_data: {}
  production_nginx: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: scram_production_django
    networks:
      - default
    depends_on:
      - postgres
      - redis
    volumes:
      - ./staticfiles:/staticfiles
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: scram_production_postgres
    networks:
      - default
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres

  nginx:
    image: nginx:1.19
    restart: on-failure:5
    depends_on:
      - django
    networks:
      - default
    volumes:
      - ./compose/production/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/scram/ssl/server.crt:/etc/ssl/server.crt
      - /etc/scram/ssl/server.key:/etc/ssl/server.key
      - ./staticfiles:/staticfiles
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"

  redis:
    image: redis:5.0
    networks:
      - default
    volumes:
      - production_redis_data:Z

  gobgp:
    image: jauderho/gobgp:v2.32.0
    networks:
      - default
      - clab
    volumes:
      - $CI_PROJECT_DIR/gobgp_config:/config:z
    ports:
      - "179"
      - "50051"

  redis_to_gobgp_translator:
    build:
      context: .
      dockerfile: ./compose/local/translator/Dockerfile
    depends_on:
      - redis
      - gobgp
    networks:
      - default

  celeryworker:
    <<: *django
    image: scram_production_celeryworker
    command: /start-celeryworker
    networks:
      - default

  celerybeat:
    <<: *django
    image: scram_production_celerybeat
    networks:
      - default
    command: /start-celerybeat

  flower:
    <<: *django
    image: scram_production_flower
    networks:
      - default
    command: /start-flower

  networks:
    default:
      enable_ipv6: true
      driver: bridge
      driver_opts:
        com.docker.network.enable_ipv6: "true"
      ipam:
        driver: default
        config:
          - subnet: 10.6.0.0/24
          - subnet: 2001:db6::/64

    clab:
      enable_ipv6: true
      driver: macvlan
      driver_opts:
        parent: scram_clab
      ipam:
        driver: default
        config:
          - subnet: 10.0.0.0/24
          - subnet: 2001:db8::/64
