version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_nginx: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: scram_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: scram_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres

  nginx:
    image: nginx:1.19
    restart: on-failure:5
    depends_on:
      - django
    volumes:
      - ./compose/production/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - production_nginx:/app/nginx
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"

  redis:
    image: redis:5.0

  celeryworker:
    <<: *django
    image: scram_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: scram_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: scram_production_flower
    command: /start-flower
